name: jardis-actions
on: [push]
jobs:
  deploy-jardis-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.15.1'
      - name: Install NPM dependencies    
        run: |
          npm install vsce
          npm install
        working-directory: jardis-client
      - name: Packaging jardis client
        run: vsce package
        working-directory: jardis-client
      - name: Copy package to artifacts
        run: |
          cp jardis-client/*.vsix ./artifacts
          ls ./artifacts
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with: 
          name: jardis-client
          path: ./artifacts
          
