name: learn-github-actions
on: [push]
jobs:
  vsce-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.15.1'
      - run: npm install -g vsce
      # - run: ls
      #   working-directory: jardis-client
      - run: vsce package
        working-directory: jardis-client