name: publish-assets
on:
  release:
    types: [published]
jobs:
  deploy-jardis-client:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: getTag
        uses: dawidd6/action-get-tag@v1
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.15.1'
      - name: Install NPM dependencies    
        run: |
          npm install vsce -g
          npm install
        working-directory: jardis-client
      - name: Packaging jardis client
        run: vsce package -o jardis-client-${{steps.getTag.outputs.tag}}.vsix
        working-directory: jardis-client
      - name: Upload Artifact
        uses: AButler/upload-release-assets@v2.0
        with:
          files: jardis-client/*.vsix
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{steps.getTag.outputs.tag}}

          
